FROM node:14-alpine AS base

WORKDIR /app

COPY ./package*.json ./


FROM base AS installer

RUN npm ci

COPY . .


FROM installer AS test

CMD ["npm", "test"]


FROM installer AS dev

CMD ["npm", "run", "dev"]


FROM base AS prod

RUN npm ci --production

COPY . .

RUN npm run build

CMD [ "npm", "start" ]
