services:
  frontend:
    build: 
      target: prod
    ports:
      - 3000:3000
    volumes:
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
      API_URL: http://backend:4000
