name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
      - name: Enter Docker Folder
        run: cd docker
      - name: Build Test Images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build
      - name: Run frontend tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up
